### ISSUE TITLE
pip install fails on Python 3.8

### ISSUE THREAD

**Issue by zulc22** [milkey-mouse/swood#28]
```
Collecting swood
  Downloading swood-1.0.4.tar.bz2 (16 kB)
Collecting mido
  Downloading mido-1.2.9-py2.py3-none-any.whl (52 kB)
     |████████████████████████████████| 52 kB 197 kB/s 
Requirement already satisfied: numpy in /usr/lib/python3.8/site-packages (from swood) (1.19.0)
Collecting progressbar2
  Downloading progressbar2-3.51.4-py2.py3-none-any.whl (25 kB)
Collecting pyfftw
  Downloading pyFFTW-0.12.0-cp38-cp38-manylinux1_x86_64.whl (2.6 MB)
     |████████████████████████████████| 2.6 MB 631 kB/s 
Collecting pillow
  Downloading Pillow-7.2.0-cp38-cp38-manylinux1_x86_64.whl (2.2 MB)
     |████████████████████████████████| 2.2 MB 1.2 MB/s 
Requirement already satisfied: six in /usr/lib/python3.8/site-packages (from progressbar2->swood) (1.15.0)
Collecting python-utils>=2.3.0
  Downloading python_utils-2.4.0-py2.py3-none-any.whl (12 kB)
Using legacy setup.py install for swood, since package 'wheel' is not installed.
Installing collected packages: mido, python-utils, progressbar2, pyfftw, pillow, swood
    Running setup.py install for swood ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-yoyevh9w/swood/setup.py'"'"'; __file__='"'"'/tmp/pip-install-yoyevh9w/swood/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-2906b0jo/install-record.txt --single-version-externally-managed --compile --install-headers /usr/include/python3.8/swood
         cwd: /tmp/pip-install-yoyevh9w/swood/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-yoyevh9w/swood/setup.py", line 128, in <module>
        for package in pip.get_installed_distributions()]
    AttributeError: module 'pip' has no attribute 'get_installed_distributions'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-yoyevh9w/swood/setup.py'"'"'; __file__='"'"'/tmp/pip-install-yoyevh9w/swood/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-2906b0jo/install-record.txt --single-version-externally-managed --compile --install-headers /usr/include/python3.8/swood Check the logs for full command output.
```

**Comment by zulc22** [comment]
cloning this repo and running setup.py to install, however, _DOES_ work. definitely something having to do with the pip package and not the program itself.

**Comment by twilligon** [comment]
pip must have changed its API some time in the last 5 years. It's the fault of my setup script which used to (and apparently still does, in the latest published version) query installed packages to see if it could use a precompiled pillow-SIMD. I removed this logic in 1ad5b1fb0eadf797b42ef5435d804a6b438e19b0 but that hasn't been published on PyPI.
